# nixpacks.toml

# [phases.setup]
# Default setup pulls `elixir`, which is 1.13.4
# nixPkgs = ['...', 'pkgs.elixir_1_15']
# nixPkgs = ['pkgs.elixir_1_15']

# [phases.build]
# cmds = ['mix release']

# [start]
# cmd = './bin/railway start'
